"""Puerto común de una sesión de simulación para clientes Web y Tkinter."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class SimulationSessionPort(Protocol):
    """Casos de uso de ejecución que deben conservar paridad entre interfaces."""

    def load_script(self, source: str) -> Any: ...

    def start(self, *, debug: bool = False, step_mode: bool = False) -> Any: ...

    def pause(self) -> Any: ...

    def resume(self) -> Any: ...

    def stop(self) -> Any: ...

    def reset(self) -> Any: ...

    def set_simulation_profile(self, profile: str, calibration: dict[str, float] | None = None) -> Any: ...

    def set_debug_breakpoints(self, breakpoints: set[int]) -> Any: ...

    def set_debug_watches(self, watches: list[str]) -> Any: ...

    def debug_continue(self) -> Any: ...

    def debug_step(self) -> Any: ...
